version: "3.3"

services:

    nginx:
        container_name: nginx
        image: nginx:1.23.3-alpine
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/certs/:/etc/nginx/certs/
        networks:
            - jellyfin
    
    jellyfin:
        container_name: jellyfin
        image: jellyfin/jellyfin
        restart: unless-stopped
        user: 1000:1000
        volumes:
        - ./jellyfin/config:/config
        - ./jellyfin/cache:/cache
        - ./jellyfin/media/:/media
        networks:
            - jellyfin

networks:
    jellyfin:
        driver: bridge
        external: true
