version: "3.9"

services:

    nginx:
        container_name: nginx
        image: nginx:1.23.3-alpine
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - host
    
    jellyfin:
        container_name: jellyfin
        image: jellyfin/jellyfin
        restart: unless-stopped
        user: 1000:1000
        volumes:
        - ./jellyfin/config:/config
        - ./jellyfin/cache:/cache
        - ./jellyfin/media/:/media
        networks:
            - host

networks:
    default:
        name: host 
        driver: bridge